// DOCX generation using the docx package
// Renders LLM-generated content into a Word document

import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  Table,
  TableRow,
  TableCell,
  WidthType,
  AlignmentType,
  BorderStyle,
  ShadingType,
} from 'docx';
import type { ExportGenerator, ExportData } from './types';
import type { GeneratedReport, GeneratedContent } from '../schemas/reportOutput';

const BRAND = {
  primary: '2B579A',
  tableHeader: '2B579A',
  tableStripe: 'F0F4FA',
};

export class DocxGenerator implements ExportGenerator {
  async generate(report: GeneratedReport, metadata: ExportData): Promise<Buffer> {
    const children: (Paragraph | Table)[] = [];

    // Title
    children.push(new Paragraph({
      text: report.title,
      heading: HeadingLevel.TITLE,
      spacing: { after: 200 },
    }));

    if (report.subtitle) {
      children.push(new Paragraph({
        children: [new TextRun({ text: report.subtitle, color: '666666', size: 28 })],
        spacing: { after: 200 },
      }));
    }

    // Metadata
    const metaLine = [metadata.docId, `v${metadata.version}`, metadata.status].filter(Boolean).join('  ·  ');
    children.push(new Paragraph({
      children: [new TextRun({ text: metaLine, color: 'A0A0A0', size: 20 })],
      spacing: { after: 400 },
    }));

    // Sections
    for (const section of report.sections) {
      children.push(new Paragraph({
        text: section.heading,
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 400, after: 200 },
      }));

      for (const block of section.content) {
        children.push(...this.renderContent(block));
      }
    }

    // Footer
    children.push(new Paragraph({
      children: [new TextRun({ text: `Generated by RQML · ${new Date().toLocaleDateString()}`, color: 'A0A0A0', size: 16 })],
      spacing: { before: 600 },
      alignment: AlignmentType.CENTER,
    }));

    const doc = new Document({
      creator: 'RQML Export',
      title: report.title,
      description: report.subtitle,
      sections: [{
        properties: {},
        children,
      }],
    });

    const buffer = await Packer.toBuffer(doc);
    return Buffer.from(buffer);
  }

  private renderContent(block: GeneratedContent): (Paragraph | Table)[] {
    switch (block.type) {
      case 'paragraph':
        return this.renderParagraph(block.text);
      case 'bullet-list':
        return this.renderBulletList(block.items);
      case 'table':
        return this.renderTable(block.headers, block.rows);
      case 'key-value':
        return this.renderKeyValue(block.pairs);
    }
  }

  private renderParagraph(text: string): Paragraph[] {
    // Split by double newlines into separate paragraphs
    return text.split(/\n\n+/).map(para =>
      new Paragraph({
        children: this.parseMarkdownInline(para.trim()),
        spacing: { after: 200 },
      })
    );
  }

  private renderBulletList(items: string[]): Paragraph[] {
    return items.map(item =>
      new Paragraph({
        children: this.parseMarkdownInline(item),
        bullet: { level: 0 },
        spacing: { after: 80 },
      })
    );
  }

  private renderTable(headers: string[], rows: string[][]): (Paragraph | Table)[] {
    const headerRow = new TableRow({
      tableHeader: true,
      children: headers.map(h =>
        new TableCell({
          children: [new Paragraph({
            children: [new TextRun({ text: h, bold: true, color: 'FFFFFF', size: 20 })],
          })],
          shading: { type: ShadingType.SOLID, color: BRAND.tableHeader },
        })
      ),
    });

    const dataRows = rows.map((row, idx) =>
      new TableRow({
        children: row.map(cell =>
          new TableCell({
            children: [new Paragraph({
              children: [new TextRun({ text: cell, size: 20 })],
            })],
            shading: idx % 2 === 1
              ? { type: ShadingType.SOLID, color: BRAND.tableStripe }
              : undefined,
          })
        ),
      })
    );

    const table = new Table({
      rows: [headerRow, ...dataRows],
      width: { size: 100, type: WidthType.PERCENTAGE },
    });

    return [
      table,
      new Paragraph({ spacing: { after: 200 } }), // spacing after table
    ];
  }

  private renderKeyValue(pairs: { key: string; value: string }[]): Paragraph[] {
    return pairs.map(p =>
      new Paragraph({
        children: [
          new TextRun({ text: `${p.key}: `, bold: true, size: 22 }),
          new TextRun({ text: p.value, size: 22 }),
        ],
        spacing: { after: 80 },
      })
    );
  }

  /**
   * Simple inline markdown parser: **bold** and *italic*
   */
  private parseMarkdownInline(text: string): TextRun[] {
    const runs: TextRun[] = [];
    const regex = /(\*\*(.+?)\*\*|\*(.+?)\*|`(.+?)`)/g;
    let lastIndex = 0;
    let match: RegExpExecArray | null;

    while ((match = regex.exec(text)) !== null) {
      if (match.index > lastIndex) {
        runs.push(new TextRun({ text: text.slice(lastIndex, match.index), size: 22 }));
      }
      if (match[2]) {
        runs.push(new TextRun({ text: match[2], bold: true, size: 22 }));
      } else if (match[3]) {
        runs.push(new TextRun({ text: match[3], italics: true, size: 22 }));
      } else if (match[4]) {
        runs.push(new TextRun({ text: match[4], font: 'Courier New', size: 20 }));
      }
      lastIndex = match.index + match[0].length;
    }

    if (lastIndex < text.length) {
      runs.push(new TextRun({ text: text.slice(lastIndex), size: 22 }));
    }

    if (runs.length === 0) {
      runs.push(new TextRun({ text, size: 22 }));
    }

    return runs;
  }
}
