// PDF generation using PDFKit
// Renders LLM-generated content into a PDF document

import PDFDocument from 'pdfkit';
import type { ExportGenerator, ExportData } from './types';
import type { GeneratedReport, GeneratedContent } from '../schemas/reportOutput';

const BRAND = {
  primary: '#2B579A',
  dark: '#333333',
  medium: '#666666',
  light: '#A0A0A0',
  tableHeader: '#2B579A',
  tableHeaderText: '#FFFFFF',
  tableStripe: '#F0F4FA',
  tableBorder: '#CCCCCC',
};

const MARGIN = 60;
const PAGE_WIDTH = 595.28; // A4
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

export class PdfGenerator implements ExportGenerator {
  async generate(report: GeneratedReport, metadata: ExportData): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({
        size: 'A4',
        margins: { top: MARGIN, bottom: MARGIN, left: MARGIN, right: MARGIN },
        info: {
          Title: report.title,
          Author: 'RQML Export',
          Subject: report.subtitle || 'RQML Specification Report',
        },
      });

      const chunks: Buffer[] = [];
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Title page
      doc.moveDown(4);
      doc.fontSize(28).fillColor(BRAND.dark).text(report.title, { align: 'center' });
      if (report.subtitle) {
        doc.moveDown(0.5);
        doc.fontSize(16).fillColor(BRAND.medium).text(report.subtitle, { align: 'center' });
      }
      doc.moveDown(1);
      const metaLine = [metadata.docId, `v${metadata.version}`, metadata.status].filter(Boolean).join('  ·  ');
      doc.fontSize(10).fillColor(BRAND.light).text(metaLine, { align: 'center' });

      // Content sections
      for (const section of report.sections) {
        doc.addPage();
        doc.fontSize(20).fillColor(BRAND.primary).text(section.heading);
        doc.moveDown(0.5);
        // Divider line
        doc.strokeColor(BRAND.tableBorder).lineWidth(0.5)
          .moveTo(MARGIN, doc.y).lineTo(PAGE_WIDTH - MARGIN, doc.y).stroke();
        doc.moveDown(0.5);

        for (const block of section.content) {
          this.renderContent(doc, block);
        }
      }

      // Footer
      doc.moveDown(2);
      doc.fontSize(8).fillColor(BRAND.light)
        .text(`Generated by RQML · ${new Date().toLocaleDateString()}`, { align: 'center' });

      doc.end();
    });
  }

  private renderContent(doc: PDFKit.PDFDocument, block: GeneratedContent): void {
    switch (block.type) {
      case 'paragraph':
        this.renderParagraph(doc, block.text);
        break;
      case 'bullet-list':
        this.renderBulletList(doc, block.items);
        break;
      case 'table':
        this.renderTable(doc, block.headers, block.rows);
        break;
      case 'key-value':
        this.renderKeyValue(doc, block.pairs);
        break;
    }
  }

  private renderParagraph(doc: PDFKit.PDFDocument, text: string): void {
    // Strip markdown formatting for PDF (simple approach)
    const cleaned = text.replace(/\*\*(.+?)\*\*/g, '$1').replace(/\*(.+?)\*/g, '$1').replace(/`(.+?)`/g, '$1');
    doc.fontSize(11).fillColor(BRAND.dark).text(cleaned, { lineGap: 4 });
    doc.moveDown(0.5);
  }

  private renderBulletList(doc: PDFKit.PDFDocument, items: string[]): void {
    for (const item of items) {
      const cleaned = item.replace(/\*\*(.+?)\*\*/g, '$1').replace(/\*(.+?)\*/g, '$1');
      doc.fontSize(11).fillColor(BRAND.dark).text(`•  ${cleaned}`, { indent: 15, lineGap: 2 });
    }
    doc.moveDown(0.5);
  }

  private renderTable(doc: PDFKit.PDFDocument, headers: string[], rows: string[][]): void {
    const colCount = headers.length;
    if (colCount === 0) return;

    const colW = CONTENT_WIDTH / colCount;
    const rowH = 22;
    const cellPad = 4;
    let y = doc.y;

    // Check if we have room for at least header + a few rows
    if (y + rowH * 3 > doc.page.height - MARGIN) {
      doc.addPage();
      y = doc.y;
    }

    // Header row
    for (let c = 0; c < colCount; c++) {
      const x = MARGIN + c * colW;
      doc.rect(x, y, colW, rowH).fill(BRAND.tableHeader);
      doc.fontSize(9).fillColor(BRAND.tableHeaderText)
        .text(headers[c], x + cellPad, y + 6, { width: colW - cellPad * 2, lineBreak: false });
    }
    y += rowH;

    // Data rows
    for (let r = 0; r < rows.length; r++) {
      if (y + rowH > doc.page.height - MARGIN) {
        doc.addPage();
        y = doc.y;
      }

      const bgColor = r % 2 === 1 ? BRAND.tableStripe : '#FFFFFF';
      for (let c = 0; c < colCount; c++) {
        const x = MARGIN + c * colW;
        doc.rect(x, y, colW, rowH).fill(bgColor);
        doc.fontSize(9).fillColor(BRAND.dark)
          .text(rows[r][c] || '', x + cellPad, y + 6, { width: colW - cellPad * 2, lineBreak: false });
      }
      y += rowH;
    }

    doc.y = y;
    doc.moveDown(0.5);
  }

  private renderKeyValue(doc: PDFKit.PDFDocument, pairs: { key: string; value: string }[]): void {
    for (const p of pairs) {
      doc.fontSize(11).fillColor(BRAND.dark)
        .font('Helvetica-Bold').text(`${p.key}: `, { continued: true })
        .font('Helvetica').text(p.value);
    }
    doc.moveDown(0.5);
  }
}
