// REQ-EXP-013 AC-02: what an exported document says about its own origin.
//
// The generators used to stamp `new Date().toLocaleDateString()` into the
// rendered footer and, for xlsx, into the workbook metadata. That made two
// exports of the same specification differ in three separate ways:
//
//   * the visible date changed with the clock, so re-exporting an unchanged
//     document produced different content;
//   * `toLocaleDateString()` changed with the machine, so the same document
//     read "7/23/2026" in the United States and "23.7.2026" in Germany — a
//     content difference no container normalisation can remove;
//   * the embedded timestamp changed every zip entry in the three OOXML
//     containers, so the bytes never matched.
//
// The provenance line now names the SPECIFICATION rather than the moment of
// rendering. That is both reproducible and more useful to a reviewer: "which
// document is this, exactly" is the question an audit artifact has to answer,
// and the wall-clock time it was printed does not answer it.

/** How a rendered document identifies its source. */
export interface Provenance {
  /** Digest of the specification source. */
  specHash: string;
  /** A date derived from the specification, not the clock. */
  date: Date;
}

/**
 * The footer line, in ISO 8601 so it reads identically in every locale.
 *
 * Falls back to the current date only when no provenance is supplied, which is
 * the language-model path — that output is not reproducible anyway.
 */
export function provenanceLine(provenance?: Provenance): string {
  if (!provenance) {
    return `Generated by RQML · ${new Date().toISOString().slice(0, 10)}`;
  }
  return `Generated by RQML · specification ${provenance.specHash}`;
}

/** The timestamp embedded in document metadata. */
export function provenanceDate(provenance?: Provenance): Date {
  return provenance?.date ?? new Date();
}
